Marketplace/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout
from accounts.views import RegisterView, LoginView, activate_user_view, AccountTypeView
from profiles.views import SearchSMEView, HomePageView, HomeActivateView, AboutView, view404
from businessplan.views import InfoView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePageView.as_view(), name='base_home'),
    url(r'^about/', AboutView.as_view(), name='about'),
    url(r'^activation/$', HomeActivateView.as_view(), name='base_home_activation'),
    url(r'^account/$', AccountTypeView.as_view(), name='account_type'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout, {'next_page': '/login/'}, name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^info/(?P<slug>[\w-]+)/$', InfoView.as_view(), name='info'),
    url(r'^profile/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    url(r'^businessplan/', include(('businessplan.urls', 'businessplan'), namespace='businessplan')),
    url(r'^diagnostics/', include(('diagnostics.urls', 'diagnostics'), namespace='diagnostics')),
    url(r'^dataroom/', include(('dataroom.urls', 'dataroom'), namespace='accordion')),
    url(r'^diligenceroom/', include(('diligence.urls', 'diligence'), namespace='diligence')),
    url(r'^kpi/', include(('kpi.urls', 'kpi'), namespace='kpi')),
    url(r'^search-companies/', SearchSMEView.as_view(), name='search-companies')
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'profiles.views.view_404'

kpi/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$',  kpi_home, name='home'),
    url(r'^follower/(?P<slug>[\w-]+)/$', KPIFollowerView.as_view(), name='detail-follower'),
    url(r'^business/(?P<slug>[\w-]+)/$', KPIBusinessView.as_view(), name='detail-business'),
    url(r'^follower/(?P<slug>[\w-]+)/api/data/$', get_data_follower, name='api-f-data'),
    url(r'^business/(?P<slug>[\w-]+)/api/data/$', get_data_business, name='api-b-data'),
    # url(r'^data', get_data, name='bussness_data'),
    # url(r'^prueba', prueba, name='prueba'),
]

kpi/models.py
from django.db import models
from django.conf import settings
from profiles.utils import sme_choices
import datetime
from django.urls import reverse
from django.db.models.signals import pre_save, post_save
from profiles.utils import unique_slug_generator
from .utils import is_year, get_period_verbose
import os

User = settings.AUTH_USER_MODEL

def get_upload_path(instance, filename):
    if is_year(filename):
        return os.path.join('Yearly', filename)
    else:
        return os.path.join('Monthly', filename)

class ExcelTemplate(models.Model):
    PERIODS = (('y', 'Year'), ('m', 'Month'))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    template = models.FileField(blank=True, null=True, upload_to=get_upload_path)
    period = models.CharField(max_length=10, choices=PERIODS, default='y')
    period_verbose = models.CharField(max_length=20, null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(null=True, blank=True)

    def get_absolute_url(self):
        return reverse('kpi:demo')

    class Meta:
        ordering = ['-updated', '-timestamp']

    def get_user(self):
        return self.user

    def get_template(self):
        return self.template

    def get_period(self):
        return self.period

    def get_period_verbose(self):
        return self.period_verbose


def pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
    if is_year(instance.template.name):
        instance.period = 'y'
    else:
        instance.period = 'm'
    if not instance.period_verbose:
        instance.period_verbose = get_period_verbose(instance)

pre_save.connect(pre_save_receiver, sender=ExcelTemplate)

kpi/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import ExcelTemplate

User = get_user_model()

class ExcelTemplateForm(forms.ModelForm):
    class Meta:
        model = ExcelTemplate
        fields = ['template']

kpi/views.py
from django.views.generic import DetailView, FormView, UpdateView, TemplateView
from businessplan.utils import try_get_context
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import ExcelTemplate
from accounts.models import User # temporary solution
from .utils import get_business_graph_data, get_follower_graph_data, add_graph_data_follower
from .forms import ExcelTemplateForm
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import redirect
from django.http import HttpResponseRedirect

# class KPIHomeView(LoginRequiredMixin, FormView):
#     template_name = 'home_view.html'
#     form_class = ExcelTemplateForm
#
#     def get_queryset(self):
#         return ExcelTemplate.objects.filter(user=self.request.user)
#
#     def form_valid(self, form):
#         obj = form.save(commit=False)
#         obj.user = self.request.user
#         return super(KPIHomeView, self).form_valid(form)
#
#     def get_context_data(self, *args, **kwargs):
#         context = super(KPIHomeView, self).get_context_data(*args, **kwargs)
#         slug = self.kwargs.get("slug")
#         if slug:
#             user = ExcelTemplate.objects.get(slug=slug).get_user()
#         else:
#             user = self.request.user
#         full_context = try_get_context(context, user)
#         return full_context
#
#     def get_success_url(self):
#         kpis = ExcelTemplate.objects.filter(user=self.request.user)
#         if kpis.count() > 1:
#             return reverse('kpi:detail-follower', kwargs={'slug': kpis.first().slug})
#         else:
#             return redirect('/kpi/')

@login_required
def kpi_home(request):
    if request.method == "GET":
        form = ExcelTemplateForm()
        context = try_get_context({}, request.user)
        context['form'] = form
        return render(request, 'home_view.html', context)
    elif request.method == 'POST':
        file = request.FILES['template']
        template = ExcelTemplate(user=request.user, template=file)
        template.save()
        # If user has less than 2 KPIs uploaded redirect to same page
        kpis = ExcelTemplate.objects.filter(user=request.user)
        if kpis.count() < 2:
            return redirect('/kpi/')
        else:
            return HttpResponseRedirect(reverse('kpi:detail-follower', kwargs={'slug': kpis.first().slug}))

class KPIFollowerView(LoginRequiredMixin, TemplateView):
    template_name = 'follower_view.html'

    def get_context_data(self, *args, **kwargs):
        context = super(KPIFollowerView, self).get_context_data(*args, **kwargs)
        slug = self.kwargs.get("slug")
        if slug:
            user = ExcelTemplate.objects.filter(slug=slug).first().get_user()
        else:
            user = self.request.user
        full_context = try_get_context(context, user)
        yearly_excel = ExcelTemplate.objects.filter(user=user, period='y').first()
        full_context = add_graph_data_follower(full_context, yearly_excel.template.file)
        return full_context

    # def get(self, request, *args, **kwargs):
    #     response = super(KPIDemoView, self).get(request, *args, **kwargs)
    #     response['X_EMAIL'] = request.user.email
    #     print(response['X_EMAIL'])
    #     return response

class KPIBusinessView(LoginRequiredMixin, TemplateView):
    template_name = 'business_view.html'

    def get_context_data(self, *args, **kwargs):
        context = super(KPIBusinessView, self).get_context_data(*args, **kwargs)
        slug = self.kwargs.get("slug")
        if slug:
            user = ExcelTemplate.objects.filter(slug=slug).first().get_user()
        else:
            user = self.request.user
        full_context = try_get_context(context, user)
        return full_context

@login_required
def get_data_follower(request, *args, **kwargs):
    slug = kwargs.get("slug")
    if slug:
        user = ExcelTemplate.objects.filter(slug=slug).first().get_user()
    else:
        user = request.user
    yearly_excel = ExcelTemplate.objects.filter(user=user, period='y').first()
    monthly_excels = ExcelTemplate.objects.filter(user=user, period='m')
    print(get_follower_graph_data(yearly_excel, monthly_excels))
    return JsonResponse(get_follower_graph_data(yearly_excel, monthly_excels))

@login_required
def get_data_business(request, *args, **kwargs):
    slug = kwargs.get("slug")
    if slug:
        user = ExcelTemplate.objects.filter(slug=slug).first().get_user()
    else:
        user = request.user
    yearly_excel = ExcelTemplate.objects.filter(user=user, period='y').first()
    monthly_excels = ExcelTemplate.objects.filter(user=user, period='m')
    print(get_business_graph_data(yearly_excel, monthly_excels, user))
    return JsonResponse(get_business_graph_data(yearly_excel, monthly_excels, user))

# def prueba(request):
#     return render(request, "kpi/business_view.html")

# Not using REST for now: this project has custom user and can't get the email from headers
# class ChartData(APIView):
#     authentication_classes = []
#     permission_classes = []
#
#     def get(self, request, format=None):
#         temporary_user = User.objects.get(email='lemac_cw@lemac.com') # temporary solution
#         print(request.META.get('HTTP_X_EMAIL'))
#         gross_and_nets = GrossAndNet.objects.filter(user=temporary_user)
#         years = []
#         gross_values = []
#         net_values = []
#         for gn in gross_and_nets:
#             years.append(gn.get_year())
#             gross_values.append(gn.get_gross())
#             net_values.append(gn.get_net())
#         data = {
#             "labels": years,
#             "gross_values": gross_values,
#             "net_values": net_values,
#         }
#         return Response(data)

kpi/templates/business_view.html
{% extends "base_white.html" %}
<script>
{% block jquery %}

var endpoint = 'api/data';
$.ajax({
	method: "GET",
	url: endpoint,
	success: function(data) {
	    idName1 = 'doughnut';
	    doughnutLabels = ['Cost of Goods Sold', 'Payroll Costs', 'Sales, General & Administrative',
			'Taxes', 'Other', 'Interest', 'Rent/Leases'];
	    expenses = data.expenses;
        idName2 = 'improvement';
        diagLabels = ['Environmental', 'Leadership', 'Financial Management',
			'Product/Services', 'Organization', 'Sales & Marketing'];
        scores = data.diag_scores;
		improvedScores = data.diag_scores_improv;
		idName3 = 'sales';
		sales = data.sales_concentration;
		salesLabels = data.sales_names;
        idName4 = 'stock';
        yearLabels = data.year_labels;
		inventoryTurns = data.inventory_turns;
		payableTurns = data.account_turns;
		idName5 = 'cash';
		cashBank = data.cash_bank;
		receivable = data.accounts_receivable;
		payable = data.accounts_payable;
		idName6 = 'product-a';
		idName7 = 'product-b';
		doughnutChart(expenses, idName1, doughnutLabels);
        polarChart(scores, improvedScores, idName2, diagLabels);
        pieChart(sales, idName3, salesLabels);
		stockChart(inventoryTurns, payableTurns, idName4, yearLabels);
		cashChart(cashBank, receivable, payable, idName5, yearLabels);
		productChart([10, 20, 85, 85], [-5, 55, 40, 60], idName6, ['January', 'February', 'March', 'April'], 'Product A');
        productChart([-5, 20, 40, 60], [10, 10, 85, 85], idName7, ['January', 'February', 'March', 'April'], 'Product B');
    },
	error: function(error_data){
		console.log("error");
		console.log(error_data)
	}
});

function polarChart(scores, improvedScores, idName, labels){
    var ctx = document.getElementById(idName).getContext('2d');
	var polar = new Chart(ctx, {
		type: 'polarArea',
		data: {
			labels: labels,
			datasets: [{
				label: 'First Scores',
				data: scores,
				backgroundColor: 'rgba(54, 162, 235, 0.2)',
				borderColor: 'rgba(54, 162, 235, 1)',
				borderWidth: 1
			},
			{
                label: 'Current Scores',
                data: improvedScores,
				backgroundColor: 'rgba(255, 159, 64, 0.2)',
				borderColor: 'rgba(255, 159, 64, 1)',
				borderWidth: 1
			}]
		},
		options: {
		    title: {
		        display: true,
				text: 'Business Diagnostics'
			},
            scale: {
		        ticks: {
		            max: 100
                }
            }
		}
	});
}

function pieChart(scores, idName, labels){
    var ctx = document.getElementById(idName).getContext('2d');
	var pie = new Chart(ctx, {
		type: 'pie',
		data: {
			labels: labels,
			datasets: [{
				label: 'First Scores',
				data: scores,
				backgroundColor: [
				    'rgba(54, 162, 235, 0.5)',
					'rgba(54, 166, 35, 0.5)',
					'rgba(255, 159, 64, 0.5)',
					'rgba(224, 108, 112)',
					'rgba(237, 191, 50)',
                    'rgba(213, 145, 238)'
					],
				borderColor: 'rgba(247, 247, 247, 1)',
				borderWidth: 8
			}]
		},
		options: {
		    title: {
		        display: true,
				text: 'Sales Concentration by Customer by Month'
			}
		}
	});
}

function doughnutChart(scores, idName, labels){
    var ctx = document.getElementById(idName).getContext('2d');
	var pie = new Chart(ctx, {
		type: 'doughnut',
		data: {
			labels: labels,
			datasets: [{
				label: 'First Scores',
				data: scores,
				backgroundColor: [
				    'rgba(54, 162, 235, 0.5)',
					'rgba(54, 166, 35, 0.5)',
					'rgba(255, 159, 64, 0.5)',
					'rgba(224, 108, 112)',
					'rgba(237, 191, 50)',
					'rgba(144, 153, 148)',
					'rgba(213, 145, 238)'
					],
				borderColor: 'rgba(247, 247, 247, 1)',
				borderWidth: 8
			}]
		},
		options: {
		    title: {
		        display: true,
				text: 'Expenses - Last Month'
			}
		}
	});
}

function productChart(orders, unfilled, idName, labels, title){
    var ctx = document.getElementById(idName).getContext('2d');
	var line = new Chart(ctx, {
		type: 'line',
		data: {
			labels: labels,
			datasets: [{
				label: 'New Orders',
				data: orders,
				fill: false,
				borderColor: [
				    'rgba(54, 162, 235, 0.5)'
					]
			},
			{
				label: 'Ending Inventory/Unfilled Orders',
				data: unfilled,
				fill: false,
				borderColor: [
					'rgba(255, 159, 64, 0.5)'
					]
			}]
		},
		options: {
		    title: {
		        display: true,
				text: title
			}
		}
	});
}

function stockChart(inventory, payable, idName, labels){
    var ctx = document.getElementById(idName).getContext('2d');
	var line = new Chart(ctx, {
		type: 'line',
		data: {
			labels: labels,
			datasets: [{
				label: 'Inventory Turns',
				data: inventory,
				fill: false,
				borderColor: [
				    'rgba(54, 162, 235, 0.5)'
					]
			},
			{
				label: 'Account Payable Turnover Ratio',
				data: payable,
				fill: false,
				borderColor: [
					'rgba(255, 159, 64, 0.5)'
					]
			}]
		},
		options: {
		    scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true,
                        callback: function (value, index, values) {
                            return value + '.00x';
                        }
                    }
                }]
            },
		    title: {
		        display: true,
				text: 'Stock Turns and Accounts Payable Turns'
			}
		}
	});
}

function cashChart(cash, receivable, payable, idName, labels){
    var ctx = document.getElementById(idName).getContext('2d');
	var line = new Chart(ctx, {
		type: 'line',
		data: {
			labels: labels,
			datasets: [{
				label: 'Cash in Bank',
				data: cash,
				fill: false,
				borderColor: [
				    'rgba(54, 162, 235, 0.5)'
					]
			},
			{
				label: 'Accounts Receivable',
				data: receivable,
				fill: false,
				borderColor: [
					'rgba(255, 159, 64, 0.5)'
					]
			},
			{
				label: 'Accounts Payable',
				data: payable,
				fill: false,
				borderColor: [
					'rgba(54, 166, 35, 0.5)'
					]
			}]
		},
		options: {
		    scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true,
                        callback: function (value, index, values) {
                            return value + '$';
                        }
                    }
                }]
            },
			title: {
				display: true,
				text: 'Cash and Receivables'
			}
		}
	});
}

{% endblock %}
</script>
{% block content %}
{% load static %}
<main role="main" class="container-fluid">
	<div class="row">
		<div class="col-lg-2 col-sm-3 no-float bar-1">
			{% include 'snippets/side_buttons.html' %}
            {% if kpi %}
            <p>{{ smeprofile.get_company_name }}'s uploaded documents:</p>
            <ul>
                {% for excelfile in kpi %}
                <li><a href={{ MEDIA_URL }}{{ excelfile.get_template.url }}>{{ excelfile.get_period_verbose }}</a></li>
                {% endfor %}
            </ul>
            {% endif %}
		</div>
		<div class="col-lg-10 col-sm-9">
			<h1 class="h1 title"> <b>Business Dashboard</b><small><a href="{% url 'kpi:home' %}" style="margin-left: 5px">Update</a></small></h1>
			<div class="row">
				<div class="col-sm-4">
					<canvas id="sales" width="100" height="100"></canvas>
				</div>
				<div class="col-sm-4">
					<canvas id="improvement" width="100" height="100"></canvas>
				</div>
				<div class="col-sm-4">
					<canvas id="doughnut" width="100" height="100"></canvas>
				</div>
			</div>
			<div class="row">
                <div class="col-sm-4">
					<canvas id="cash" width="100" height="100"></canvas>
				</div>
                <div class="col-sm-4">
					<canvas id="stock" width="100" height="100"></canvas>
				</div>
				<div class="col-sm-4">
					<canvas id="product-a" width="100" height="100"></canvas>
				</div>
			</div>
			<div class="row">
				<div class="col-sm-4">
					<canvas id="product-b" width="100" height="100"></canvas>
				</div>
			</div>
		</div>
	</div>
</main>
{% endblock content %}

kpi/templates/follower_view.html
{% extends "base_white.html" %}

{% block styles %}<link rel="stylesheet" type="text/css" href="/static/css/follower_kpi.css">{% endblock styles %}
<script>
{% block jquery %}

var endpoint = 'api/data';
$.ajax({
	method: "GET",
	url: endpoint,
	success: function(data) {
	    idName1 = 'grossandnet';
        grosslabels = data.gross_labels;
        grossValues = data.gross;
        netValues = data.net;
        idName2 = 'flow';
        flowLabels = data.flow_labels;
		revenues = data.revenue;
		expenditures = data.expenses;
		cashFlow = data.cash_flow;
		idName3 = 'sales';
		salesLabels = data.sales_names;
		sales = data.sales_concentration;
		idName4 = 'speedo';
		salesLabels_speedo = ['Actual', 'Projected - Actual'];
		sales_speedo = [data.actual_sales, data.forecast_sales - data.actual_sales];
		barChart(grossValues, netValues, idName1, grosslabels);
        flowChart(revenues, expenditures, cashFlow, idName2, flowLabels);
        pieChart(sales, idName3, salesLabels);
        speedoChart(sales_speedo, idName4, salesLabels_speedo);
    },
	error: function(error_data){
		console.log("error");
		console.log(error_data)
	}
});

function barChart(gross, net, idName, labels){
    var ctx = document.getElementById(idName).getContext('2d');
	var grossandnet = new Chart(ctx, {
		type: 'bar',
		data: {
			labels: labels,
			datasets: [{
				label: 'Gross profit margin',
				data: gross,
				backgroundColor: 'rgba(54, 162, 235, 0.5)',
				borderColor: 'rgba(54, 162, 235, 1)',
				borderWidth: 1
			},
			{
                label: 'Net profit margin',
                data: net,
				backgroundColor: 'rgba(255, 159, 64, 0.5)',
				borderColor: 'rgba(255, 159, 64, 0.5)',
				borderWidth: 1
			}]
		},
		options: {
		    scales: {
		        yAxes: [{
		            ticks: {
		                beginAtZero:true,
						max: 100,
						callback: function(value, index, values) {
                        	return value + '%';
                    	}
		            },
					gridLines: {
		                display: false
					}
		        }],
				xAxes: [{
					gridLines: {
		                display: false
					}
		        }]
		    },
		    title: {
		        display: true,
				text: 'Profit Margins by Year'
			}
		}
	});
}
function flowChart(revenues, expenditures, cashFlow, idName, labels){
    var ctx = document.getElementById(idName).getContext('2d');
	var flow = new Chart(ctx, {
		type: 'bar',
		data: {
			labels: labels,
			datasets: [{
				label: 'Cash Flow',
				data: cashFlow,
                stack: 0,
				backgroundColor: 'rgba(237, 191, 50)',
				borderColor: 'rgba(237, 191, 50)',
				borderWidth: 1
			},
			{
				label: 'Revenues',
				data: revenues,
                stack:0,
				backgroundColor: 'rgba(54, 166, 35, 0.5)',
				borderColor: 'rgba(54, 166, 35, 0.5)',
				borderWidth: 1
			},
      {
        label: 'Expenditures',
        data: expenditures,
        stack:0,
				backgroundColor: 'rgba(224, 108, 112)',
				borderColor: 'rgba(224, 108, 112)',
				borderWidth: 1
			},
            ]
		},
		options: {
		    scales: {
		        yAxes: [{
		            ticks: {
		                beginAtZero:true
		            },
					gridLines: {
		                display: true
					},
					stacked:false
		        }],
				xAxes: [{
					gridLines: {
		                display: false
					},
					stacked:true
		        }]
		    },
		    title: {
		        display: true,
				text: 'Cash flow by Month'
			}
		}
	});
}
function pieChart(scores, idName, labels){
    var ctx = document.getElementById(idName).getContext('2d');
	var pie = new Chart(ctx, {
		type: 'pie',
		data: {
			labels: labels,
			datasets: [{
				label: 'First Scores',
				data: scores,
				backgroundColor: [
				    'rgba(54, 162, 235, 0.5)',
					'rgba(54, 166, 35, 0.5)',
					'rgba(255, 159, 64, 0.5)',
					'rgba(224, 108, 112)',
					'rgba(237, 191, 50)',
                    'rgba(213, 145, 238)'
					],
				borderColor: 'rgba(247, 247, 247, 1)',
				borderWidth: 8
			}]
		},
		options: {
		    title: {
		        display: true,
				text: 'Sales Concentration by Customer by Year'
			}
		}
	});
}
function speedoChart(scores, idName, labels){
    var ctx = document.getElementById(idName).getContext('2d');
	var speedo = new Chart(ctx, {
		type: 'doughnut',
		data: {
			labels: labels,
			datasets: [{
				label: 'Scores',
				data: scores,
				backgroundColor: [
				    'rgba(54, 162, 235, 0.5)',
					'rgba(54, 166, 35, 0.5)',
					],
				borderColor: 'rgba(247, 247, 247, 1)',
				borderWidth: 8
			}]
		},
		options: {
		    rotation: -Math.PI,
		    circumference: Math.PI,
		    title: {
		        display: true,
				text: 'Sales Actual vs Forecast'
			}
		}
	});
}
{% endblock %}
</script>
{% block content %}
{% load static %}
<main role="main" class="container-fluid">
	<div class="row">
		<div class="col-lg-2 col-sm-3 no-float bar-1">
			{% include 'snippets/side_buttons.html' %}
            {% if kpi %}
            <p>{{ smeprofile.get_company_name }}'s uploaded documents:</p>
            <ul>
                {% for excelfile in kpi %}
                <li><a href={{ MEDIA_URL }}{{ excelfile.get_template.url }}>{{ excelfile.get_period_verbose }}</a></li>
                {% endfor %}
            </ul>
            {% endif %}
		</div>
		<div class="col-lg-10 col-sm-9">
			<h1 class="h1 title"> <b>Follower Dashboard</b><small><a href="{% url 'kpi:home' %}" style="margin-left: 5px">Update</a></small></h1>
            <div class="row">
                <div class="col-sm-4">
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-sales">Sales</div>
                        <div class="panel-body">{{ sales }} {{ smeprofile.get_currency }}</div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-net">Net Income</div>
                        <div class="panel-body">{{ net_income }} {{ smeprofile.get_currency }}</div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-default">
                        <div class="panel-heading panel-heading-cash">Cash</div>
                        <div class="panel-body">{{ cash }} {{ smeprofile.get_currency }}</div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <canvas id="speedo" width="100" height="100"></canvas>
                </div>
								<div class="col-sm-4">
                    <canvas id="grossandnet" width="100" height="100"></canvas>
                </div>
                <div class="col-sm-4">
                    <div class="panel-group">
                          <div class="panel panel-default">
                          <div class="panel-heading">Accounts Receivable</div>
                          <div class="panel-body">{{ accounts_receivable }} {{ smeprofile.get_currency }}</div>
                        </div>
                        <div class="panel panel-default">
                          <div class="panel-heading">Accounts Payable</div>
                          <div class="panel-body">{{ accounts_payable }} {{ smeprofile.get_currency }}</div>
                        </div>
                        <div class="panel panel-default">
                          <div class="panel-heading"><b>Quick Ratio</b></div>
                          <div class="panel-body">{{ quick_ratio }} to 1</div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading"><b>Current Ratio</b></div>
                          <div class="panel-body">{{ current_ratio }} to 1</div>
                        </div>
                      </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <canvas id="sales" width="100" height="100"></canvas>
                </div>
								<div class="col-sm-8">
										<canvas id="flow" width="200" height="100"></canvas>
                </div>
            </div>
		</div>
	</div>
</main>
{% endblock content %}