Marketplace/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import logout
from accounts.views import RegisterView, LoginView, activate_user_view, AccountTypeView
from profiles.views import SearchSMEView, HomePageView, HomeActivateView, AboutView, view404
from businessplan.views import InfoView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomePageView.as_view(), name='base_home'),
    url(r'^about/', AboutView.as_view(), name='about'),
    url(r'^activation/$', HomeActivateView.as_view(), name='base_home_activation'),
    url(r'^account/$', AccountTypeView.as_view(), name='account_type'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout, {'next_page': '/login/'}, name='logout'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^activate/(?P<code>[a-z0-9].*)/$', activate_user_view, name='activate'),
    url(r'^info/(?P<slug>[\w-]+)/$', InfoView.as_view(), name='info'),
    url(r'^profile/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    url(r'^businessplan/', include(('businessplan.urls', 'businessplan'), namespace='businessplan')),
    url(r'^diagnostics/', include(('diagnostics.urls', 'diagnostics'), namespace='diagnostics')),
    url(r'^dataroom/', include(('dataroom.urls', 'dataroom'), namespace='accordion')),
    url(r'^diligenceroom/', include(('diligence.urls', 'diligence'), namespace='diligence')),
    url(r'^kpi/', include(('kpi.urls', 'kpi'), namespace='kpi')),
    url(r'^search-companies/', SearchSMEView.as_view(), name='search-companies')
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'profiles.views.view_404'

kpi/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^$',  kpi_home, name='home'),
    url(r'^follower/(?P<slug>[\w-]+)/$', KPIFollowerView.as_view(), name='detail-follower'),
    url(r'^business/(?P<slug>[\w-]+)/$', KPIBusinessView.as_view(), name='detail-business'),
    url(r'^follower/(?P<slug>[\w-]+)/api/data/$', get_data_follower, name='api-f-data'),
    url(r'^business/(?P<slug>[\w-]+)/api/data/$', get_data_business, name='api-b-data'),
    # url(r'^data', get_data, name='bussness_data'),
    # url(r'^prueba', prueba, name='prueba'),
]

templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

templates/snippets/js.html
<script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>

templates/snippets/navbar.html
{% load static %}
<!--
<nav class="navbar navbar-light bg-faded" style="background-color: #565656;">
	<div class="container-fluid">
	  <a class="navbar-brand" href="#">
	    <img src="{% static 'logos/logo.png' %}" height="30" class="logo pull-left"/></a>
	    <span class="name pull-left">CHALLENGES MARKETPLACE</span>
	</div>
</nav>
-->
{% block styles %} <link rel="stylesheet" type="text/css" href="/static/css/navbar.css"> {% endblock styles%}

<nav class="navbar navbar-default">
	<div class="container-fluid nav-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-nav-demo" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
	  		</button>
			<a href="#" class="navbar-brand">
				<img src="{% static 'logos/logo.png' %}" height="30" class="pull-left">
			</a>
			<span class="name pull-left"><b>CHALLENGES MARKETPLACE</b></span>
		</div>
	</div>
</nav>

templates/snippets/navbar_white.html
{% load static %}
{% block styles %} <link rel="stylesheet" type="text/css" href="/static/css/navbar_white.css"> {% endblock styles%}

<nav class="navbar navbar-default">
	<div class="container-fluid nav-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-nav-demo" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
	  		</button>
			<a href="/" class="navbar-brand"><img src="{% static 'logos/logo.png' %}" height="30" class="pull-left"></a>
			<span class="name pull-left"><b>CHALLENGES MARKETPLACE</b></span>
		</div>
		<div class="collapse navbar-collapse" id="bs-nav-demo">
			<form class="navbar-form navbar-left" role="search">
				<div class="form-group">
					<input type="text" class="form-control" placeholder="Search..." name="query" value="{{ request.GET.query }}">
				</div>
			</form>
			<ul class="nav navbar-nav">

					<li><a href="/search-companies/" id="nav-names">SMEs</a></li>
          {% if smeprofile %}
          <li><a style="color:white" href="/profile/sme/{{ smeprofile.slug }}/">{{ smeprofile.get_company_name }}'s Info</a></li>
          {% endif %}
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
						<!--<img src="{% static 'logos/logo-white.png' %}" height="30" class="pull-left">-->
						<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li>
                            {% if user.is_staff %}
								<a href="{{ staffprofile.get_absolute_url }}">Profile</a>
							{% elif user.is_sme %}
								<a href="{{ smeprofile.get_absolute_url }}">Profile</a>
							{% else %}
								<a href="/profile/sme/create">Profile</a>
							{% endif %}
						</li>
						<li role="separator" class="divider"></li>
						<li><a href="{% url 'logout' %}">Logout</a></li>
					</ul>
				</li>
	 		 </ul>
		</div>
	</div>
</nav>

templates/snippets/side_buttons.html
<div class="nav-buttons" style="margin-top:80px;">
    {% if kpi is not None %}
        <form action="{% url 'kpi:detail-follower' slug=kpi.first.slug %}">
            <button class="button standard" type="submit">Follower Dashboard</button>
        </form>
        <div class="progress progress-buttons" style="margin-top:-55px; margin-bottom: 40px;">
            <div class="progress-bar progress-bar-buttons" role="progressbar" aria-valuenow="50"
                 aria-valuemin="0" aria-valuemax="100" style="width:100%; background-image: none; background-color: #B0AFAF;">
            </div>
        </div>
        <form action="{% url 'kpi:detail-business' slug=kpi.first.slug %}">
            <button class="button standard" type="submit">Business Dashboard</button>
        </form>
        <div class="progress progress-buttons" style="margin-top:-55px; margin-bottom: 40px;">
            <div class="progress-bar progress-bar-buttons" role="progressbar" aria-valuenow="50"
                 aria-valuemin="0" aria-valuemax="100" style="width:100%; background-image: none; background-color: #B0AFAF;">
            </div>
        </div>
    {% else %}
        <form action="/kpi/">
            <button class="button standard" style="color: #B0AFAF;" type="submit">Follower Dashboard</button>
        </form>
        <form action="/kpi/">
            <button class="button standard" style="color: #B0AFAF;" type="submit">Business Dashboard</button>
        </form>
    {% endif %}
    {% if bp is not None %}
        <form action="{{ bp.get_absolute_url }}">
            <button class="button standard" type="submit">Business Plan</button>
        </form>
    <div class="progress progress-buttons" style="margin-top:-55px; margin-bottom: 40px;">
        <div class="progress-bar progress-bar-buttons" role="progressbar" aria-valuenow="50"
             aria-valuemin="0" aria-valuemax="100" style="width:100%; background-image: none; background-color: #B0AFAF;">
        </div>
      </div>
    {% else %}
        <form action="/businessplan/">
            <button class="button standard" style="color: #B0AFAF;" type="submit">Business Plan</button>
        </form>
    {% endif %}
    {% if diag is not None %}
        <form action="{{ diag.get_absolute_url }}">
            <button class="button standard" type="submit">Organizational Strengthening</button>
        </form>
    <div class="progress progress-buttons" style="margin-top:-55px; margin-bottom: 40px;">
        <div class="progress-bar progress-bar-buttons" role="progressbar" aria-valuenow="50"
             aria-valuemin="0" aria-valuemax="100" style="width:100%; background-image: none; background-color: #B0AFAF;">
        </div>
      </div>
    {% else %}
        <form action="/diagnostics/">
            <button class="button standard" style="color: #B0AFAF;" type="submit">Organizational Strengthening</button>
        </form>
    {% endif %}
    {% if diligence is not None %}
        <form action="{{ diligence.get_absolute_url }}">
            <button class="button standard" type="submit">Diligence Checklist</button>
        </form>
    <div class="progress progress-buttons" style="margin-top:-55px; margin-bottom: 40px;">
        <div class="progress-bar progress-bar-buttons" role="progressbar" aria-valuenow="50"
             aria-valuemin="0" aria-valuemax="100" style="width:100%; background-image: none; background-color: #B0AFAF;">
        </div>
      </div>
    {% else %}
        <form action="/diligenceroom/">
            <button class="button standard" style="color: #B0AFAF;" type="submit">Diligence Checklist</button>
        </form>
    {% endif %}
    {% if accordion is not None %}
        <form action="{{ accordion.get_absolute_url }}">
            <button class="button standard" type="submit">Data Room</button>
        </form>
    <div class="progress progress-buttons" style="margin-top:-55px; margin-bottom: 40px;">
        <div class="progress-bar progress-bar-buttons" role="progressbar" aria-valuenow="50"
             aria-valuemin="0" aria-valuemax="100" style="width:40%; background-image: none; background-color: #B0AFAF;">
        </div>
      </div>
    {% else %}
        <form action="/dataroom/">
            <button class="button standard" style="color: #B0AFAF;" type="submit">Data Room</button>
        </form>
    {% endif %}
</div>